"""initial tables

Revision ID: 38809398bb7f
Revises: 
Create Date: 2026-04-18 23:54:21.107029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38809398bb7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=200), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('campo_modificado', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.String(length=200), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comisiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('partidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('diputados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('partido_id', sa.UUID(), nullable=False),
    sa.Column('salario', sa.Integer(), nullable=False),
    sa.Column('monto_gasolina', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diputado_comision',
    sa.Column('diputado_id', sa.UUID(), nullable=False),
    sa.Column('comision_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comision_id'], ['comisiones.id'], ),
    sa.ForeignKeyConstraint(['diputado_id'], ['diputados.id'], ),
    sa.PrimaryKeyConstraint('diputado_id', 'comision_id')
    )
    op.create_table('proyectos_ley',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('texto_completo', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('presentado', 'en_comision', 'en_debate', 'votado', 'aprobado', 'archivado', name='estadoproyecto'), nullable=False),
    sa.Column('fecha_presentacion', sa.String(length=10), nullable=False),
    sa.Column('proponente_id', sa.UUID(), nullable=False),
    sa.Column('comision_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comision_id'], ['comisiones.id'], ),
    sa.ForeignKeyConstraint(['proponente_id'], ['diputados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_ley_codigo'), 'proyectos_ley', ['codigo'], unique=True)
    op.create_table('cambios_estado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('presentado', 'en_comision', 'en_debate', 'votado', 'aprobado', 'archivado', name='estadoproyecto'), nullable=False),
    sa.Column('estado_nuevo', sa.Enum('presentado', 'en_comision', 'en_debate', 'votado', 'aprobado', 'archivado', name='estadoproyecto'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.String(length=200), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_ley.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_ley.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyecto_tema',
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('tema_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_ley.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['temas.id'], ),
    sa.PrimaryKeyConstraint('proyecto_id', 'tema_id')
    )
    op.create_table('votos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('diputado_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Enum('a_favor', 'en_contra', 'abstencion', 'ausente', name='valorvoto'), nullable=False),
    sa.ForeignKeyConstraint(['diputado_id'], ['diputados.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_ley.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('proyecto_tema')
    op.drop_table('documentos')
    op.drop_table('cambios_estado')
    op.drop_index(op.f('ix_proyectos_ley_codigo'), table_name='proyectos_ley')
    op.drop_table('proyectos_ley')
    op.drop_table('diputado_comision')
    op.drop_table('diputados')
    op.drop_table('temas')
    op.drop_table('partidos')
    op.drop_table('comisiones')
    op.drop_table('bitacora')
    # ### end Alembic commands ###
